### ISSUE TITLE
image optimization

### ISSUE THREAD

**Issue by slowkow** [SimonEnsemble/SimonEnsemble.github.io#8]
Hi Cory, I found your page via Twitter ([link][1]).

[1]: https://twitter.com/non_manifold/status/1105459320316018688

Just wanted to let you know about these image optimization tools:

- https://squoosh.app (web app, just drag and drop)
- https://imageoptim.com/mac (desktop app, overwrites your images by default)

The banner image on your home page weighs a whopping **37.8 MB**:

https://github.com/SimonEnsemble/SimonEnsemble.github.io/blob/master/images/hartscove.JPG

With squoosh I could get it down to **457 KB** without any noticeable loss in quality, unless you zoom in to the details.

You might consider optimizing all of your images, so visitors don't have to wait a long time to download so much data when browsing your website.

**Comment by SimonEnsemble** [comment]
@slowkow wow, that was a large image file. Thanks for letting me know; I just put up a smaller image.

Also thanks for pointing out my blog post being Tweeted!
